id: tokyodev
name: TokyoDev Developer Survey
domain: tokyodev.com
responsesCollectionName: responses
normalizedCollectionName: normalized_responses
locales: en-US, ja-JP

emailOctopus:
  listId: b3169680-5dbd-11ee-bb23-97d390c4feaa
