id: td2024
# shareUrl: https://stateofjs.com
questionsUrl: https://surveys.tokyodev.com/en-US/survey/tokyodev/2024
resultsUrl: https://2024.surveys.tokyodev.com/
issuesUrl: https://github.com/tokyodev-inc/tokyodev-devographics/issues/
discordUrl: https://discord.gg/yBGceZ6Swg
year: 2024
status: 1 # preview/open/closed/hidden
resultsStatus: 1 # hidden/preview/published
# imageUrl: https://tokyodev-assets.onrender.com/images/surveys/html2023.png
# faviconUrl: https://devographics.github.io/surveys/state_of_js/js2022/images/js2022-favicon.svg
# socialImageUrl: https://devographics.github.io/surveys/state_of_js/js2022/images/js2022-og.png
enableSkip: true
enableReadingList: false
startedAt: October 5, 2023
endedAt: October 31, 2023
hashtag: TokyoDev

faq:
  - tokyodev_td2023
  - survey_goals_td2023
  - data_used_td2023
  - who_should_take_survey_td2023
  - how_long_will_survey_take_td2023
  - results_released_td2023

credits:
  - id: michelle_tan
    role: survey_review
  - id: paulo_d_alberti
    role: survey_review
  - id: scott_rothrock
    role: survey_review
  - id: grace_icay
    role: survey_review
  - id: minh_lai
    role: survey_review
  - id: mathieu_mayer
    role: survey_review

sources:
  - id: tokyodev
  - id: reddit
  - id: linkedin
  - id: facebook
  - id: twitter
  - id: work
  - id: hn_tokyo
  - id: word_of_mouth
  - id: le_wagon
  - id: tokyo_rubyist_meetup
